sudo: false
language: node_js
node_js:
  - 8
before_install:
  - npm install -g codecov
script:
  - npm run test:bs
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: hUly4dPlJw3lnrKNRGnI0PyNC9GA+pgCI/XKZ3h1umafMdxHRWlu/0uCgkvQWnV6+YQxMzk2Y1w2/mgMUFmy3mch8xuvwc6opNdmLVxse0fe4WAAWTTPXvQV3eW1fiGsme9smqQoyuy6br2fwrQJ8S6qMEr8BpyrG9eZPUKU/b4VWHq5VxUYBqcs00JBjw62ZGtAkF6v1xl2J4KHctfVYuMPvhhx3ExlWf9TVMxm8G4cUjVII2uKMrkbNHxaD/EMidFcZk2k0Y121XvlR0IAaLbldOLwBAKE6mXZMTuE+f+95jKNAKeSwdjcruwPsEj6HEsngxj4WFa2fq8CbUC2malEsobuzRfZKbwVB4pUxwXgQ6r5s8DeQMDgUYnjtLoNI5qAYUJEs2VoC7SIrkUoSqReOatYrUVHoNb/jkixADrwbr4Py3iT6wgW+esiMuGiy9sbayogkN7SO4vTyVIY8CShdxPBMiVFSmbSBUkoCR1NiCgA6BD56+XbHbGE9KJ3RVmCLCi0AcH6yJPiOXsun+lQhOYZED6TfgYgCKHfGGk0DAU+8pgcPq71XeYszhI4NxN9wJXSnCpH7qybwZoSrrAg7SrDDPM61e2OAIsEoiE6ed7QvMyT5EYUqOXEcqm8zNTJcKh8eBskujwW1f4V4hZjYGn6NnR3ocDvwTkR93M=
    - secure: BbpFQUNw3Uz9sI36YCOoDG6Su5HVEdJHlwtcqj/cH+hxxbi2RTKLxR/vZ2ISeDY5OgEebzl8YoDQoa7me5ThZhR8rA2wi5VY5lm0j56n42Q8HS7c0HAmBRYO51eje5GJNrlFq2T45pKYHIIPsWCbcjWTR3g5R7GgTwFR4xEldAHQt+YmlNUqgtOJ8naOvnU8O4iwfok0nPUdOhC/p+x/umiOyOiRK7dW3+9Fs21rVZjz51Y+Yp7SMSW59X6ZEGjSmlBc+aYjWXJz5sFza6S18y9k6QnrEnKRXQM0kuT1LEDCLNO2wqTVce2IIRHtDk4p0zlgjSZaPEHGA65pIPVs/Hu07ZtyDbNempu1Vm5FbVfQL4/DokE63s2ASef2nIENFiBWzEjhE37eZ/okkRB9iBlDPqGC/N7RRR679/M9wZCXMpjAl3poA8XGAisujek8LTN7UcM7lGXP+nXnQyKjPpRhAUaKOV3E9+ouNq1hfcuo7KU7DBR049gqp7Vpt+57MHI8GAwqy+i/dTukbIpv6mSvaP6HMPzmcjjCPd7VQUJ/up3hDimRHhJsJPZM6TUvsjcB5YbZEZ9eyfgJq03x7QYOe7QYjY4YOydxjYWP/5UTQdffv2bBmNRVZDsXQOBU8xILFcsGEnzyochW5Za+Cbvc2zT7sEGnRKCE+sAFTH8=
